# SETUP:
# Do it after AD SYNC demo

# Verification:
# select * from dba_tab_privs where grantee = 'DEPARTMENT_HR';

- hosts: localhost
  vars:
    oraclehost: orcl
    oracle_env:
#      ORACLE_HOME: /usr/lib/oracle/12.1/client64
#      LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
      nothing_to_see_here: just a placeholder
  tasks:
    - block:

        - name: Manage what objects DEPARTMENT_HR can access
          oracle_privs:
            ### Target Oracle database connection information
            hostname: "{{ oraclehost }}"
            port: 1521
            service_name: orcl
            user: system
            password: oracle
            ###
            roles:
              - DEPARTMENT_HR
            privs:
              - SELECT
              - FLASHBACK
            objs:
              - HR.%
              - HRREST.COUNTRIES
            objtypes:
              - TABLE
              - VIEW
            state: present

      environment: "{{ oracle_env }}"
